In [1]:
import numpy as np
import random

In [2]:
File_data = np.loadtxt("input1.txt", dtype=int) 

X = [0]*File_data.shape[1]

for i in range(File_data.shape[1]):
    X[i] = File_data[:,i]

X = np.array(X)
print(X)

[[0 0 1 0 0 0]
 [1 1 0 0 0 1]
 [0 0 0 1 1 0]
 [1 0 1 0 1 0]]


In [3]:
n_of_docs = X.shape[0]
n_of_shingles = X.shape[1]

rand = [1,2,3,4,5,6]
random.seed(1)

permutation_matrix = [0]*4

for i in range(n_of_docs):
    rand = [1,2,3,4,5,6]
    random.shuffle(rand)
    permutation_matrix[i] = rand.copy()

In [4]:
permutation_matrix = np.array(permutation_matrix)

In [5]:
# Part 1

signature_matrix = np.zeros((n_of_docs, n_of_docs), dtype=int)

for i in range(permutation_matrix.shape[0]):
    for j in range(X.shape[0]):
        temp = permutation_matrix[i] * X[j]
        idx = np.where(temp != 0)[0]
        signature_matrix[i][j] = min(temp[idx])
        
        
print("Permutation Matrix:")
print(permutation_matrix)
print("\nSignature Matrix:")
print(signature_matrix)

Permutation Matrix:
[[3 4 6 1 5 2]
 [1 2 3 5 6 4]
 [3 6 5 4 1 2]
 [6 2 3 1 5 4]]

Signature Matrix:
[[6 2 1 3]
 [3 1 5 1]
 [5 2 1 1]
 [3 2 1 3]]


In [6]:
with open('output.txt', 'w') as file:
    for i in range(signature_matrix.shape[0]):
        for j in range(signature_matrix.shape[1]):
            file.write(str(signature_matrix[i][j]))
            file.write(" ")
        file.write("\n")
        
    for i in range(X.shape[0]):
        for j in range(i+1,X.shape[0]):
            temp = X[i] + X[j]
            n1 = np.sum(temp == 1)
            n2 = np.sum(temp == 2)
            col = float(n2/(n1+n2))
            print("col (d{}, d{}):".format(i+1,j+1), col)
            file.write("{:.2f} ".format(col))
    file.write("\n")
            
    for i in range(signature_matrix.shape[0]):
        for j in range(i+1,signature_matrix.shape[0]):
            n = np.sum(signature_matrix[:,i] == signature_matrix[:,j])
            sig = float(n/signature_matrix.shape[0])
            print("sim (d{}, d{}):".format(i+1,j+1), sig)
            file.write("{:.2f} ".format(sig))
    file.write("\n")
    
    probability = 0.6
    bands = 10
    rows = 4
    simi = 1-(1-probability**rows)**bands 
    print(simi)
    file.write("{:.2f} ".format(simi))
    file.write("\n")

col (d1, d2): 0.0
col (d1, d3): 0.0
col (d1, d4): 0.3333333333333333
col (d2, d3): 0.0
col (d2, d4): 0.2
col (d3, d4): 0.25
sim (d1, d2): 0.0
sim (d1, d3): 0.0
sim (d1, d4): 0.25
sim (d2, d3): 0.0
sim (d2, d4): 0.25
sim (d3, d4): 0.25
0.7504320431679077
